version: "2"
services:
  django:
    image: {{cookiecutter.project_slug}}/web
    container_name: {{cookiecutter.project_slug}}_django
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    stdin_open: true
    working_dir: /usr/app/django
    tty: true
    command: "/bin/bash"
    links:
      - postgres:postgres
    environment:
      PYTHONPATH: /usr/app/django/project:/usr/app/django/project/vendor
      DJANGO_SETTINGS_MODULE: app.config.settings.local
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_DOTENV_LOCATION: .pipenv
      SHELL: /bin/bash
    logging:
      driver: none

  postgres:
    {% if cookiecutter.use_geo.lower() == "y" %}image: mdillon/postgis{% else %}image: postgres:latest{% endif %}
    container_name: {{cookiecutter.project_slug}}_postgres
    restart: always
    volumes:
      - /usr/lib/postgresql
      - .:/usr/app/django
    environment:
     POSTGRES_USER: djangodb
     POSTGRES_PASSWORD: djangodb
    logging:
      driver: none
